NumPy Assignment: Banking Industry Analysis - Questions Only
Dataset Overview
The assignment uses banking industry data with 10 rows × 5 columns:

Customer_ID: Unique identifier for each customer
Account_Balance: Customer's account balance in dollars
Credit_Score: Customer's credit score (300-900 range)
Transaction_Count: Number of transactions in the last month
Years_Active: Number of years the customer has been with the bank



In [1]:
# Columns: [Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active]

import numpy as np

banking_data = np.array([
    [101, 12000, 720, 15, 5],
    [102, 4500, 650, 8, 2],
    [103, 18000, 810, 22, 10],
    [104, 2500, 390, 3, 1],
    [105, 9800, 700, 12, 4],
    [106, 22000, 860, 30, 12],
    [107, 1500, 310, 1, 0],
    [108, 13400, 755, 18, 7],
    [109, 7600, 680, 9, 3],
    [110, 30000, 900, 40, 15]
])


In [2]:

# Question 1: Array Creation and Manipulation

# Q1.1: Create a 4x4 identity matrix using np.eye()

identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
# Q1.2: Create an array of 8 zeros using np.zeros()

zeros = np.zeros(8)
print(zeros)


[0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# Q1.3: Create an array of 6 ones using np.ones()

ones = np.ones(6)
print(ones)

[1. 1. 1. 1. 1. 1.]


In [5]:

# Q1.4: Create an array with values from 0 to 15 using np.arange()

array = np.arange(0,15)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [6]:

# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

value = np.linspace(0,100,8)
print(value)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [7]:
# Question 2: Array Attributes and Information

# Q2.1: What is the shape of the banking_data array?

shape = banking_data.shape
print(shape)

(10, 5)


In [8]:
# Q2.2: What is the data type of the banking_data array?

data_type = banking_data.dtype
print(data_type)


int64


In [9]:
# Q2.3: What is the size (total number of elements) of the banking_data array?

Size = banking_data.size
print(Size)

50


In [10]:
# Q2.4: What is the number of dimensions of the banking_data array?

dimension = banking_data.ndim
print(dimension)


2


In [11]:
# Q2.5: What is the memory size of the banking_data array in bytes?

memory_size = banking_data.nbytes
print(memory_size)

400


In [12]:
# Question 3: Indexing and Slicing

# Q3.1: Extract the first row of banking_data

first_row = banking_data[0,:]
print(first_row)

[  101 12000   720    15     5]


In [13]:

# Q3.2: Extract the last row of banking_data

last_row =banking_data[-1,:]
print(last_row)


[  110 30000   900    40    15]


In [14]:

# Q3.3: Extract the Account_Balance column (column index 1)

Account_Balance = banking_data[:,1]
print(Account_Balance)


[12000  4500 18000  2500  9800 22000  1500 13400  7600 30000]


In [15]:
# Q3.4: Extract the first 4 rows and first 3 columns

rows_column = banking_data[0:4,0:3]
print(rows_column)


[[  101 12000   720]
 [  102  4500   650]
 [  103 18000   810]
 [  104  2500   390]]


In [16]:
# Q3.5: Extract rows 3 to 7 (inclusive)

extract_rows = banking_data[3:8,:]
print(extract_rows)

[[  104  2500   390     3     1]
 [  105  9800   700    12     4]
 [  106 22000   860    30    12]
 [  107  1500   310     1     0]
 [  108 13400   755    18     7]]


In [17]:
# Question 4: Mathematical Operations

# Q4.1: Calculate the sum of all account balances

sum_account_balance = banking_data[:,1].sum()
print(sum_account_balance)

121300


In [18]:
# Q4.2: Calculate the mean account balance

calculate_mean = banking_data[:,1].mean()
print(calculate_mean)

12130.0


In [19]:

# Q4.3: Calculate the standard deviation of account balances

standard_deviation = np.std(banking_data[:,1])
print(standard_deviation)

8618.242280186836


In [20]:
# Q4.4: Calculate the variance of account balances

variance = np.var(banking_data[:,1])
print(variance)

74274100.0


In [21]:
# Q4.5: Calculate the median account balance

calculate_median = np.var(banking_data[:,1])
print(calculate_mean)

12130.0


In [22]:
# Question 5: Statistical Functions

# Q5.1: Find the minimum and maximum account balances

min_bal = min(banking_data[:,1])
print(min_bal)


max_bal = max(banking_data[:,1])
print(max_bal)


1500
30000


In [23]:
# Q5.2: Find the minimum and maximum credit scores

max_credit_scores = max(banking_data[:,2])
print(max_credit_scores)

min_credit_scores = min(banking_data[:,2])
print(min_credit_scores)

900
310


In [24]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)

percentile = np.percentile(banking_data[:,1],[25,50,75])
print(percentile)


[ 5275. 10900. 16850.]


In [25]:
# Q5.4: Calculate the correlation between account balance and credit score

correlation = np.corrcoef(banking_data[:,1],banking_data[:,2])
print(correlation)

[[1.         0.86405812]
 [0.86405812 1.        ]]


In [26]:
# Q5.5: Calculate the covariance between account balance and credit score

covariance = np.cov(banking_data[:,1], banking_data[:,2])
print(covariance)

[[8.25267778e+07 1.49658333e+06]
 [1.49658333e+06 3.63513889e+04]]


In [27]:
# Question 6: Array Reshaping and Manipulation

# Q6.1: Reshape the banking_data to 5 rows × 10 columns

reshape = banking_data.reshape(5,10)
print(reshape)

[[  101 12000   720    15     5   102  4500   650     8     2]
 [  103 18000   810    22    10   104  2500   390     3     1]
 [  105  9800   700    12     4   106 22000   860    30    12]
 [  107  1500   310     1     0   108 13400   755    18     7]
 [  109  7600   680     9     3   110 30000   900    40    15]]


In [28]:
# Q6.2: Flatten the banking_data to a 1D array

flatten_data = banking_data.flatten()
print(flatten_data)

[  101 12000   720    15     5   102  4500   650     8     2   103 18000
   810    22    10   104  2500   390     3     1   105  9800   700    12
     4   106 22000   860    30    12   107  1500   310     1     0   108
 13400   755    18     7   109  7600   680     9     3   110 30000   900
    40    15]


In [29]:
# Q6.3: Transpose the banking_data

Transpose = banking_data.T
print(Transpose)

[[  101   102   103   104   105   106   107   108   109   110]
 [12000  4500 18000  2500  9800 22000  1500 13400  7600 30000]
 [  720   650   810   390   700   860   310   755   680   900]
 [   15     8    22     3    12    30     1    18     9    40]
 [    5     2    10     1     4    12     0     7     3    15]]


In [30]:
# Q6.4: Split the banking_data into 2 equal parts vertically

vertically_split = np.vsplit(banking_data,2)
print(vertically_split)

[array([[  101, 12000,   720,    15,     5],
       [  102,  4500,   650,     8,     2],
       [  103, 18000,   810,    22,    10],
       [  104,  2500,   390,     3,     1],
       [  105,  9800,   700,    12,     4]]), array([[  106, 22000,   860,    30,    12],
       [  107,  1500,   310,     1,     0],
       [  108, 13400,   755,    18,     7],
       [  109,  7600,   680,     9,     3],
       [  110, 30000,   900,    40,    15]])]


In [31]:
# Q6.5: Split the banking_data into 2 equal parts horizontally

# horizontall_split = np.hsplit(banking_data,2)
# print(horizontall_split)


In [32]:

# Question 7: Logical Operations and Filtering

# Q7.1: Find customers with account balance greater than $100,000

balance = banking_data[banking_data[:,1] > 100000]
print(balance)

[]


In [33]:

# Q7.2: Find customers with credit score greater than 800

credit_score = banking_data[banking_data[:,2] > 800]
print(credit_score)


[[  103 18000   810    22    10]
 [  106 22000   860    30    12]
 [  110 30000   900    40    15]]


In [34]:

# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750

customers = banking_data[(banking_data[:,3]>50) & (banking_data[:,2]>750)]
print(customers)

[]


In [35]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000

# Q7.5: Find the index of the customer with the highest credit score

In [36]:
# Question 8: Sorting and Searching

# Q8.1: Sort the banking_data by account balance (ascending)

account = np.sort(banking_data[:,1])
print(account)

[ 1500  2500  4500  7600  9800 12000 13400 18000 22000 30000]


In [37]:
# Q8.2: Sort the banking_data by credit score (descending)

credit_score = np.sort(banking_data[:,2])
print(credit_score)

[310 390 650 680 700 720 755 810 860 900]


In [38]:

# Q8.3: Find the indices that would sort the array by years active

sort_values = np.argsort(banking_data[:,-1])
print(sort_values)

[6 3 1 8 4 0 7 2 5 9]


In [39]:

# Q8.4: Find the customer with the second highest account balance

second_highest = np.argsort(banking_data[:,1])
second_highest_index = second_highest[-2]
print(banking_data[second_highest_index])


[  106 22000   860    30    12]


In [40]:
# Q8.5: Find the customer with the lowest transaction count

lowest_transcation = np.argsort(banking_data[:,-2])
index = lowest_transcation[0]
print(banking_data[index])

[ 107 1500  310    1    0]


In [41]:

# Question 9: Mathematical Functions

# Q9.1: Calculate the absolute values of all elements

absolute_value = np.abs(banking_data)
print(absolute_value)

[[  101 12000   720    15     5]
 [  102  4500   650     8     2]
 [  103 18000   810    22    10]
 [  104  2500   390     3     1]
 [  105  9800   700    12     4]
 [  106 22000   860    30    12]
 [  107  1500   310     1     0]
 [  108 13400   755    18     7]
 [  109  7600   680     9     3]
 [  110 30000   900    40    15]]


In [42]:
# Q9.2: Calculate the square root of all account balances

square_root = np.sqrt(banking_data[:,1])
print(square_root)

[109.5445115   67.08203932 134.16407865  50.          98.99494937
 148.32396974  38.72983346 115.75836903  87.17797887 173.20508076]


In [43]:

# Q9.3: Calculate the square of all credit scores

square = np.square(banking_data[:2])
print(square)



[[    10201 144000000    518400       225        25]
 [    10404  20250000    422500        64         4]]


In [44]:

# Q9.4: Calculate the exponential of all transaction counts

exponential = np.exp(banking_data[:,3])
print(exponential)

[3.26901737e+06 2.98095799e+03 3.58491285e+09 2.00855369e+01
 1.62754791e+05 1.06864746e+13 2.71828183e+00 6.56599691e+07
 8.10308393e+03 2.35385267e+17]


In [45]:

# Q9.5: Calculate the natural logarithm of all account balances

natural_logarithm = np.log(banking_data[:,1])
print(natural_logarithm)

[ 9.39266193  8.41183268  9.79812704  7.82404601  9.19013766  9.99879773
  7.31322039  9.50300999  8.93590353 10.30895266]


In [46]:

# Question 10: Advanced Operations

# Q10.1: Calculate the cumulative sum of account balances

cumulative_sum = np.cumsum(banking_data[:,1])
print(cumulative_sum) 

[ 12000  16500  34500  37000  46800  68800  70300  83700  91300 121300]


In [47]:

# Q10.2: Calculate the cumulative product of transaction counts

cumulative_product =  np.cumprod(banking_data[:,3])
print(cumulative_product)


[         15         120        2640        7920       95040     2851200
     2851200    51321600   461894400 18475776000]


In [48]:

# Q10.3: Calculate the difference between consecutive account balances

difference = np.diff(banking_data[:,1])
print(difference)

[ -7500  13500 -15500   7300  12200 -20500  11900  -5800  22400]


In [49]:

# Q10.4: Calculate the gradient of account balances

gradient = np.gradient(banking_data[:,1])
print(gradient)

[-7500.  3000. -1000. -4100.  9750. -4150. -4300.  3050.  8300. 22400.]


In [50]:
# Q10.5: Calculate the histogram of account balances with 5 bins

result = np.histogram(banking_data[:,1],bins=5)

In [51]:

# Question 11: Random Numbers and Simulation

# Q11.1: Generate 6 random integers between 1 and 1000

random_number = np.random.randint(1,100,(6))
print(random_number)



[23 53 65 85 15 66]


In [52]:
# Q11.2: Generate 6 random floats between 0 and 1

random_floats = np.random.rand(6)
print(random_floats)


[0.71705487 0.32698951 0.34470792 0.94329338 0.28197029 0.65492327]


In [53]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)

numbers = np.random.normal(loc = 700 ,scale = 100, size=6)
print(numbers)

[793.27522297 562.03915386 813.51994595 668.65619956 634.90242949
 766.01188742]


In [54]:

# Q11.4: Shuffle the banking_data rows randomly

np.random.shuffle(banking_data)
print(banking_data)

[[  104  2500   390     3     1]
 [  101 12000   720    15     5]
 [  105  9800   700    12     4]
 [  106 22000   860    30    12]
 [  110 30000   900    40    15]
 [  107  1500   310     1     0]
 [  103 18000   810    22    10]
 [  108 13400   755    18     7]
 [  102  4500   650     8     2]
 [  109  7600   680     9     3]]


In [55]:
# Q11.5: Set random seed to 123 and generate 4 random numbers

np.random.seed(123)
random_num = np.random.random((6))
print(random_num)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646]


In [56]:

# Question 12: Linear Algebra Operations

# Q12.1: Calculate the dot product of account balance and credit score columns

dot_product = np.dot(banking_data[:,1],banking_data[:,2])
print(dot_product)



95650000


In [57]:
# Q12.2: Calculate the cross product of first two rows

cross_product = np.cross(banking_data[0,:3],banking_data[1,:3])
print(cross_product)



[-2880000   -35490   995500]


In [58]:
# Q12.3: Calculate the norm (magnitude) of the account balance column

norm_magnitude = np.linalg.norm(banking_data[1,:])
print(norm_magnitude)


12022.015263673558


In [59]:

# Q12.4: Create a 3x3 matrix and calculate its determinant

matrix_3_3 = np.random.randint(0,100,(3,3))
print(matrix_3_3)


[[86 97 96]
 [47 73 32]
 [46 96 25]]


In [60]:
# Q12.5: Calculate the inverse of the 3x3 matrix

inverse_matrix = np.linalg.inv(matrix_3_3)
print(inverse_matrix)

[[-0.03854595  0.20991623 -0.12067633]
 [ 0.00918055 -0.0700442   0.05440326]
 [ 0.03567123 -0.11727613  0.05313592]]


In [61]:
# Question 13: String Operations

# Q13.1: Convert all customer IDs to strings

convert = banking_data[:,0].astype(str)
print(convert)



['104' '101' '105' '106' '110' '107' '103' '108' '102' '109']


In [62]:
# Q13.2: Check if any customer ID contains '100'

check = banking_data[100  in  banking_data[0:,0] ]
print(check)

# Q13.3: Convert all customer IDs to uppercase (if they were strings)


[]


In [63]:

# Q13.4: Count the length of each customer ID string

count_length = banking_data[0:,0].astype(str)
length = np.char.str_len(count_length)
print(length)



[3 3 3 3 3 3 3 3 3 3]


In [64]:
# Q13.5: Replace '101' with 'CUST' in customer IDs

replace = np.char.replace(count_length,'101','CUST')
print(replace)

['104' 'CUST' '105' '106' '110' '107' '103' '108' '102' '109']


In [65]:

# Question 14: Date and Time Operations

# Q14.1: Convert years active to months

years_into_month = banking_data[:,-1]*12
print(years_into_month)



[ 12  60  48 144 180   0 120  84  24  36]


In [66]:
# Q14.2: Calculate the average years active

average_years = np.average(banking_data[:,-1])
print(average_years)


5.9


In [67]:

# Q14.3: Find customers who have been active for more than 5 years

customers_active = banking_data[banking_data[:,-1] >  5]
print(customers_active)



[[  106 22000   860    30    12]
 [  110 30000   900    40    15]
 [  103 18000   810    22    10]
 [  108 13400   755    18     7]]


In [68]:
# Q14.4: Calculate the total time all customers have been active (in years)

total_time = banking_data[:,-1]
print(total_time)



[ 1  5  4 12 15  0 10  7  2  3]


In [69]:
# Q14.5: Find the customer with the shortest time active

shortest_time = np.min(banking_data[:,-1])
print(shortest_time)

0
